/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameihm;

import com.sun.media.sound.WaveFileReader;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javazoom.jl.player.Player;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;


/**
 *
 * @author nassim
 */
public class GameScreen extends javax.swing.JFrame {

    // private props
    
    
    private Thread thread;
    public Game game;
    
    private String currentLetter;
    private int currentAnimal;
    
    private AudioStream backAudio;
    private AudioStream audio;
            
    
    private final String[] animals = {"Alligator","Bear","Cat","Dog","Elephant","Fish","Giraffe","Horse","Iguana","Jaguar","Kangaroo","Lion","Monkey","Newt","Octopus","Platypus","Quail","Raccoon","Snake","Toucan","Urial","Vulture","Worm","X-ray fish","Yak","Zebra"};

    private DrawArea paint;
    
    
    public GameScreen() {
        
        initComponents();
        
        //initializing current letter
        currentLetter = "A";
        currentAnimal = 0;
        
        //initialising the game
        game = new Game(gamePanel, score, life, target);
        game.init();
        
        //adding paint
        paint = new DrawArea();
        paintArea.setLayout(new BorderLayout());
        paintArea.add(paint , BorderLayout.CENTER);

        
        
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        screen = new javax.swing.JLayeredPane();
        home = new javax.swing.JPanel();
        btnPlay = new javax.swing.JLabel();
        btn1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnLearn = new javax.swing.JLabel();
        btn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnDraw = new javax.swing.JLabel();
        btn3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        screenPlay = new javax.swing.JPanel();
        gamePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        target = new javax.swing.JLabel();
        life = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        screenLearn = new javax.swing.JPanel();
        alphabetLetterB = new javax.swing.JLabel();
        alphabetLetterC = new javax.swing.JLabel();
        alphabetLetterD = new javax.swing.JLabel();
        alphabetLetterE = new javax.swing.JLabel();
        alphabetLetterF = new javax.swing.JLabel();
        alphabetLetter6 = new javax.swing.JLabel();
        alphabetLetter7 = new javax.swing.JLabel();
        alphabetLetter8 = new javax.swing.JLabel();
        alphabetLetter9 = new javax.swing.JLabel();
        alphabetLetter10 = new javax.swing.JLabel();
        alphabetLetterA = new javax.swing.JLabel();
        alphabetLetter12 = new javax.swing.JLabel();
        alphabetLetter13 = new javax.swing.JLabel();
        alphabetLetter14 = new javax.swing.JLabel();
        alphabetLetter15 = new javax.swing.JLabel();
        alphabetLetter27 = new javax.swing.JLabel();
        alphabetLetter16 = new javax.swing.JLabel();
        alphabetLetter17 = new javax.swing.JLabel();
        alphabetLetter18 = new javax.swing.JLabel();
        alphabetLetter19 = new javax.swing.JLabel();
        alphabetLetter20 = new javax.swing.JLabel();
        alphabetLetter21 = new javax.swing.JLabel();
        alphabetLetter22 = new javax.swing.JLabel();
        alphabetLetter23 = new javax.swing.JLabel();
        alphabetLetter24 = new javax.swing.JLabel();
        alphabetLetter25 = new javax.swing.JLabel();
        btnSingleLetterScreen = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        skyBackground = new javax.swing.JLabel();
        screenDraw = new javax.swing.JPanel();
        paintArea = new javax.swing.JPanel();
        blueColorBtn = new javax.swing.JLabel();
        redColorBtn = new javax.swing.JLabel();
        yellowColorBtn = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        blackColorBtn = new javax.swing.JLabel();
        orangeColorBtn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        currentLetterToDraw = new javax.swing.JLabel();
        currentLetterToDraw2 = new javax.swing.JLabel();
        screenLearnSingle = new javax.swing.JPanel();
        btnPrevLetter = new javax.swing.JLabel();
        btnNextLetter = new javax.swing.JLabel();
        imgCurrentLetter = new javax.swing.JLabel();
        animalNameLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        skyBackground1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        home.setBackground(new java.awt.Color(188, 28, 36));
        home.setLayout(null);

        btnPlay.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(254, 254, 254));
        btnPlay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPlay.setText("Play");
        btnPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
        });
        home.add(btnPlay);
        btnPlay.setBounds(70, 550, 190, 60);

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/Shape 12.png"))); // NOI18N
        home.add(btn1);
        btn1.setBounds(70, 550, 200, 60);

        jPanel1.setBackground(new java.awt.Color(211, 193, 0));
        jPanel1.setLayout(null);

        btnLearn.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnLearn.setForeground(new java.awt.Color(254, 254, 254));
        btnLearn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLearn.setText("Learn");
        btnLearn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLearn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLearnMouseClicked(evt);
            }
        });
        jPanel1.add(btnLearn);
        btnLearn.setBounds(70, 550, 190, 60);

        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/Shape 12.png"))); // NOI18N
        jPanel1.add(btn);
        btn.setBounds(70, 550, 200, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/albert_dictionary-300x279.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 160, 200, 180);

        jLabel18.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(254, 254, 254));
        jLabel18.setText("and catch it in terms of time.");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(70, 450, 300, 30);

        jLabel19.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(254, 254, 254));
        jLabel19.setText("tech your kid to focus on letters");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(70, 430, 300, 30);

        jLabel20.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(254, 254, 254));
        jLabel20.setText("Catch me, is a game designed to");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(70, 410, 300, 30);

        jLabel21.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(254, 254, 254));
        jLabel21.setText("ABC animals");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(70, 370, 220, 40);

        home.add(jPanel1);
        jPanel1.setBounds(460, 0, 460, 770);

        jPanel4.setBackground(new java.awt.Color(253, 151, 83));
        jPanel4.setLayout(null);

        btnDraw.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnDraw.setForeground(new java.awt.Color(254, 254, 254));
        btnDraw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDraw.setText("Draw");
        btnDraw.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDrawMouseClicked(evt);
            }
        });
        jPanel4.add(btnDraw);
        btnDraw.setBounds(70, 550, 190, 60);

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/Shape 12.png"))); // NOI18N
        jPanel4.add(btn3);
        btn3.setBounds(70, 550, 200, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/albert_coloring-300x279.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(130, 160, 200, 180);

        jLabel22.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(254, 254, 254));
        jLabel22.setText("and catch it in terms of time.");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(70, 450, 300, 30);

        jLabel23.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(254, 254, 254));
        jLabel23.setText("tech your kid to focus on letters");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(70, 430, 300, 30);

        jLabel24.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(254, 254, 254));
        jLabel24.setText("Catch me, is a game designed to");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(70, 410, 300, 30);

        jLabel25.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(254, 254, 254));
        jLabel25.setText("Draw it");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(70, 370, 190, 40);

        home.add(jPanel4);
        jPanel4.setBounds(920, 0, 450, 770);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/albert_apps-300x279.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        home.add(jLabel3);
        jLabel3.setBounds(130, 160, 200, 180);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Save the letter");
        home.add(jLabel6);
        jLabel6.setBounds(70, 370, 190, 40);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("and catch it in terms of time.");
        home.add(jLabel7);
        jLabel7.setBounds(70, 450, 300, 30);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Catch me, is a game designed to");
        home.add(jLabel8);
        jLabel8.setBounds(70, 410, 300, 30);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("tech your kid to focus on letters");
        home.add(jLabel9);
        jLabel9.setBounds(70, 430, 300, 30);

        screenPlay.setBackground(new java.awt.Color(211, 193, 0));
        screenPlay.setLayout(null);

        gamePanel.setBackground(new java.awt.Color(211, 193, 0));
        gamePanel.setLayout(null);
        screenPlay.add(gamePanel);
        gamePanel.setBounds(230, 20, 910, 590);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel11.setText("Pause");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        screenPlay.add(jLabel11);
        jLabel11.setBounds(50, 480, 110, 60);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/back.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        screenPlay.add(jLabel12);
        jLabel12.setBounds(50, 50, 90, 70);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel13.setText("Start");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        screenPlay.add(jLabel13);
        jLabel13.setBounds(50, 420, 100, 60);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/hole.png"))); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gamePanel, org.jdesktop.beansbinding.ObjectProperty.create(), jLabel14, org.jdesktop.beansbinding.BeanProperty.create("labelFor"));
        bindingGroup.addBinding(binding);

        screenPlay.add(jLabel14);
        jLabel14.setBounds(220, 580, 940, 150);

        target.setFont(new java.awt.Font("Ubuntu", 1, 70)); // NOI18N
        target.setText("A");
        screenPlay.add(target);
        target.setBounds(60, 300, 60, 70);

        life.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        life.setText("* * * * * ");
        screenPlay.add(life);
        life.setBounds(50, 160, 100, 30);

        score.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        score.setText("score: ");
        screenPlay.add(score);
        score.setBounds(50, 200, 170, 30);

        screenLearn.setBackground(new java.awt.Color(188, 28, 36));
        screenLearn.setLayout(null);

        alphabetLetterB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/B1.png"))); // NOI18N
        alphabetLetterB.setText("B");
        alphabetLetterB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alphabetLetterBMouseClicked(evt);
            }
        });
        screenLearn.add(alphabetLetterB);
        alphabetLetterB.setBounds(290, 90, 140, 110);

        alphabetLetterC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/C1.png"))); // NOI18N
        alphabetLetterC.setText("C");
        alphabetLetterC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alphabetLetterCMouseClicked(evt);
            }
        });
        screenLearn.add(alphabetLetterC);
        alphabetLetterC.setBounds(450, 90, 140, 110);

        alphabetLetterD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/D1.png"))); // NOI18N
        alphabetLetterD.setText("D");
        alphabetLetterD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alphabetLetterDMouseClicked(evt);
            }
        });
        screenLearn.add(alphabetLetterD);
        alphabetLetterD.setBounds(610, 90, 140, 110);

        alphabetLetterE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/E1.png"))); // NOI18N
        alphabetLetterE.setText("E");
        alphabetLetterE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alphabetLetterEMouseClicked(evt);
            }
        });
        screenLearn.add(alphabetLetterE);
        alphabetLetterE.setBounds(780, 80, 140, 130);

        alphabetLetterF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/F1.png"))); // NOI18N
        alphabetLetterF.setText("F");
        alphabetLetterF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alphabetLetterFMouseClicked(evt);
            }
        });
        screenLearn.add(alphabetLetterF);
        alphabetLetterF.setBounds(940, 90, 140, 110);

        alphabetLetter6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/G1.png"))); // NOI18N
        alphabetLetter6.setText("G");
        alphabetLetter6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alphabetLetter6MouseClicked(evt);
            }
        });
        screenLearn.add(alphabetLetter6);
        alphabetLetter6.setBounds(1080, 80, 140, 130);

        alphabetLetter7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/H1.png"))); // NOI18N
        alphabetLetter7.setText("H");
        screenLearn.add(alphabetLetter7);
        alphabetLetter7.setBounds(200, 230, 140, 110);

        alphabetLetter8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/I1.png"))); // NOI18N
        alphabetLetter8.setText("I");
        screenLearn.add(alphabetLetter8);
        alphabetLetter8.setBounds(360, 230, 140, 110);

        alphabetLetter9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/J1.png"))); // NOI18N
        alphabetLetter9.setText("J");
        screenLearn.add(alphabetLetter9);
        alphabetLetter9.setBounds(530, 230, 140, 110);

        alphabetLetter10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/K1.png"))); // NOI18N
        alphabetLetter10.setText("K");
        screenLearn.add(alphabetLetter10);
        alphabetLetter10.setBounds(690, 230, 140, 110);

        alphabetLetterA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/A1.png"))); // NOI18N
        alphabetLetterA.setText("A");
        alphabetLetterA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alphabetLetterAMouseClicked(evt);
            }
        });
        screenLearn.add(alphabetLetterA);
        alphabetLetterA.setBounds(130, 90, 140, 110);

        alphabetLetter12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/Z1.png"))); // NOI18N
        alphabetLetter12.setText("Z");
        screenLearn.add(alphabetLetter12);
        alphabetLetter12.setBounds(780, 510, 140, 110);

        alphabetLetter13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/Y1.png"))); // NOI18N
        alphabetLetter13.setText("Y");
        screenLearn.add(alphabetLetter13);
        alphabetLetter13.setBounds(610, 510, 140, 110);

        alphabetLetter14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/X1.png"))); // NOI18N
        alphabetLetter14.setText("X");
        screenLearn.add(alphabetLetter14);
        alphabetLetter14.setBounds(450, 510, 140, 110);

        alphabetLetter15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/W1.png"))); // NOI18N
        alphabetLetter15.setText("R");
        screenLearn.add(alphabetLetter15);
        alphabetLetter15.setBounds(290, 510, 140, 110);

        alphabetLetter27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/V1.png"))); // NOI18N
        alphabetLetter27.setText("V");
        screenLearn.add(alphabetLetter27);
        alphabetLetter27.setBounds(130, 510, 140, 110);

        alphabetLetter16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/P1.png"))); // NOI18N
        alphabetLetter16.setText("P");
        screenLearn.add(alphabetLetter16);
        alphabetLetter16.setBounds(530, 370, 140, 110);

        alphabetLetter17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/O1.png"))); // NOI18N
        alphabetLetter17.setText("O");
        screenLearn.add(alphabetLetter17);
        alphabetLetter17.setBounds(370, 370, 140, 110);

        alphabetLetter18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/N1.png"))); // NOI18N
        alphabetLetter18.setText("N");
        screenLearn.add(alphabetLetter18);
        alphabetLetter18.setBounds(200, 370, 140, 110);

        alphabetLetter19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/M1.png"))); // NOI18N
        alphabetLetter19.setText("M");
        screenLearn.add(alphabetLetter19);
        alphabetLetter19.setBounds(1000, 230, 140, 110);

        alphabetLetter20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/L1.png"))); // NOI18N
        alphabetLetter20.setText("L");
        screenLearn.add(alphabetLetter20);
        alphabetLetter20.setBounds(850, 230, 140, 110);

        alphabetLetter21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/U1.png"))); // NOI18N
        alphabetLetter21.setText("U");
        screenLearn.add(alphabetLetter21);
        alphabetLetter21.setBounds(1080, 510, 140, 110);

        alphabetLetter22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/T1.png"))); // NOI18N
        alphabetLetter22.setText("T");
        screenLearn.add(alphabetLetter22);
        alphabetLetter22.setBounds(920, 510, 140, 110);

        alphabetLetter23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/S1.png"))); // NOI18N
        alphabetLetter23.setText("S");
        screenLearn.add(alphabetLetter23);
        alphabetLetter23.setBounds(1020, 370, 140, 110);

        alphabetLetter24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/R1.png"))); // NOI18N
        alphabetLetter24.setText("R");
        screenLearn.add(alphabetLetter24);
        alphabetLetter24.setBounds(860, 370, 140, 110);

        alphabetLetter25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/100/Q1.png"))); // NOI18N
        alphabetLetter25.setText("Q");
        screenLearn.add(alphabetLetter25);
        alphabetLetter25.setBounds(690, 370, 140, 110);

        btnSingleLetterScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/rightArrow.png"))); // NOI18N
        btnSingleLetterScreen.setText("jLabel4");
        btnSingleLetterScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSingleLetterScreenMouseClicked(evt);
            }
        });
        screenLearn.add(btnSingleLetterScreen);
        btnSingleLetterScreen.setBounds(1230, 330, 90, 80);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/back.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        screenLearn.add(jLabel10);
        jLabel10.setBounds(50, 50, 90, 70);

        skyBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/skyScreen.png"))); // NOI18N
        screenLearn.add(skyBackground);
        skyBackground.setBounds(0, 0, 1413, 795);

        screenDraw.setBackground(new java.awt.Color(253, 151, 83));
        screenDraw.setLayout(null);

        paintArea.setBackground(new java.awt.Color(243, 241, 185));
        paintArea.setLayout(null);

        blueColorBtn.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        blueColorBtn.setForeground(new java.awt.Color(22, 110, 252));
        blueColorBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blueColorBtn.setText("~");
        blueColorBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blueColorBtnMouseClicked(evt);
            }
        });
        paintArea.add(blueColorBtn);
        blueColorBtn.setBounds(10, 60, 50, 30);

        redColorBtn.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        redColorBtn.setForeground(new java.awt.Color(252, 22, 60));
        redColorBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redColorBtn.setText("~");
        redColorBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redColorBtnMouseClicked(evt);
            }
        });
        paintArea.add(redColorBtn);
        redColorBtn.setBounds(10, 90, 50, 30);

        yellowColorBtn.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        yellowColorBtn.setForeground(new java.awt.Color(252, 206, 22));
        yellowColorBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yellowColorBtn.setText("~");
        yellowColorBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yellowColorBtnMouseClicked(evt);
            }
        });
        paintArea.add(yellowColorBtn);
        yellowColorBtn.setBounds(10, 120, 50, 30);

        jLabel26.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(45, 43, 35));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Clear");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        paintArea.add(jLabel26);
        jLabel26.setBounds(10, 190, 50, 40);

        blackColorBtn.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        blackColorBtn.setForeground(new java.awt.Color(5, 4, 0));
        blackColorBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blackColorBtn.setText("~");
        blackColorBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blackColorBtnMouseClicked(evt);
            }
        });
        paintArea.add(blackColorBtn);
        blackColorBtn.setBounds(10, 30, 50, 30);

        orangeColorBtn.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        orangeColorBtn.setForeground(new java.awt.Color(252, 110, 22));
        orangeColorBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orangeColorBtn.setText("~");
        orangeColorBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orangeColorBtnMouseClicked(evt);
            }
        });
        paintArea.add(orangeColorBtn);
        orangeColorBtn.setBounds(10, 150, 50, 30);

        screenDraw.add(paintArea);
        paintArea.setBounds(860, 50, 450, 610);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/albert_coloring-300x279.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        screenDraw.add(jLabel5);
        jLabel5.setBounds(580, 280, 190, 170);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/back.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        screenDraw.add(jLabel15);
        jLabel15.setBounds(50, 50, 90, 70);

        currentLetterToDraw.setFont(new java.awt.Font("5yearsoldfont", 1, 200)); // NOI18N
        currentLetterToDraw.setForeground(new java.awt.Color(243, 241, 185));
        currentLetterToDraw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentLetterToDraw.setText("A a");
        currentLetterToDraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                currentLetterToDrawMouseClicked(evt);
            }
        });
        screenDraw.add(currentLetterToDraw);
        currentLetterToDraw.setBounds(120, 200, 440, 330);

        currentLetterToDraw2.setFont(new java.awt.Font("5yearsoldfont", 1, 150)); // NOI18N
        currentLetterToDraw2.setForeground(new java.awt.Color(1, 1, 1));
        currentLetterToDraw2.setText("A a");
        screenDraw.add(currentLetterToDraw2);
        currentLetterToDraw2.setBounds(970, 280, 920, 170);

        screenLearnSingle.setBackground(new java.awt.Color(188, 28, 36));
        screenLearnSingle.setLayout(null);

        btnPrevLetter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/leftArrow.png"))); // NOI18N
        btnPrevLetter.setText("jLabel4");
        btnPrevLetter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrevLetterMouseClicked(evt);
            }
        });
        screenLearnSingle.add(btnPrevLetter);
        btnPrevLetter.setBounds(50, 340, 90, 80);

        btnNextLetter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/rightArrow.png"))); // NOI18N
        btnNextLetter.setText("jLabel4");
        btnNextLetter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextLetterMouseClicked(evt);
            }
        });
        screenLearnSingle.add(btnNextLetter);
        btnNextLetter.setBounds(1230, 330, 90, 80);

        imgCurrentLetter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/400/A1.png"))); // NOI18N
        imgCurrentLetter.setText("jLabel4");
        imgCurrentLetter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgCurrentLetterMouseClicked(evt);
            }
        });
        screenLearnSingle.add(imgCurrentLetter);
        imgCurrentLetter.setBounds(670, 210, 390, 340);

        animalNameLabel.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        animalNameLabel.setForeground(new java.awt.Color(72, 163, 71));
        animalNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        animalNameLabel.setText("Alligator");
        animalNameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                animalNameLabelMouseClicked(evt);
            }
        });
        screenLearnSingle.add(animalNameLabel);
        animalNameLabel.setBounds(720, 550, 290, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/back.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        screenLearnSingle.add(jLabel4);
        jLabel4.setBounds(50, 50, 90, 70);

        skyBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/desertScreen.png"))); // NOI18N
        screenLearnSingle.add(skyBackground1);
        skyBackground1.setBounds(0, 0, 1413, 795);

        screen.setLayer(home, javax.swing.JLayeredPane.DEFAULT_LAYER);
        screen.setLayer(screenPlay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        screen.setLayer(screenLearn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        screen.setLayer(screenDraw, javax.swing.JLayeredPane.DEFAULT_LAYER);
        screen.setLayer(screenLearnSingle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout screenLayout = new javax.swing.GroupLayout(screen);
        screen.setLayout(screenLayout);
        screenLayout.setHorizontalGroup(
            screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 1394, Short.MAX_VALUE)
            .addGroup(screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(screenPlay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(screenLearn, javax.swing.GroupLayout.DEFAULT_SIZE, 1394, Short.MAX_VALUE))
            .addGroup(screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(screenDraw, javax.swing.GroupLayout.DEFAULT_SIZE, 1394, Short.MAX_VALUE))
            .addGroup(screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(screenLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(screenLearnSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 1394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        screenLayout.setVerticalGroup(
            screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(screenPlay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
            .addGroup(screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(screenLearn, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
            .addGroup(screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(screenDraw, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
            .addGroup(screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(screenLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(screenLearnSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(screen)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(screen, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
        // TODO add your handling code here:
        switchScreen(screenPlay);
    }//GEN-LAST:event_btnPlayMouseClicked

    private void btnLearnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLearnMouseClicked
        // TODO add your handling code here:
        switchScreen(screenLearn);
    }//GEN-LAST:event_btnLearnMouseClicked

    private void btnDrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDrawMouseClicked
        // TODO add your handling code here:
        switchScreen(screenDraw);
        
        /*
        JFrame tempFrame =  new JFrame();
        tempFrame.setAlwaysOnTop(true);
        tempFrame.setSize(1394, 794);
        tempFrame.add(new JPanel extends PaintPanel() {}());
        tempFrame.setVisible(true); */
        
    }//GEN-LAST:event_btnDrawMouseClicked

    private void btnSingleLetterScreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSingleLetterScreenMouseClicked
        // TODO add your handling code here:
        switchScreen(screenLearnSingle);
    }//GEN-LAST:event_btnSingleLetterScreenMouseClicked

    private void btnNextLetterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextLetterMouseClicked
        // TODO add your handling code here:
        updateCurrentLetter(1);
    }//GEN-LAST:event_btnNextLetterMouseClicked

    private void alphabetLetterAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alphabetLetterAMouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount() == 2) {
            switchScreen(screenLearnSingle);
        } else
        playAudio("/home/nassim/NetBeansProjects/gameIhm/src/gameihm/sounds/letters/Letter "+"A"+" - Phonics.wav");
    }//GEN-LAST:event_alphabetLetterAMouseClicked

    private void imgCurrentLetterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgCurrentLetterMouseClicked
        // TODO add your handling code here:
                playAudio("/home/nassim/NetBeansProjects/gameIhm/src/gameihm/sounds/animalSound/"+ currentLetter.toLowerCase() + "1Sound.wav");

    }//GEN-LAST:event_imgCurrentLetterMouseClicked

    private void animalNameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_animalNameLabelMouseClicked
        // TODO add your handling code here:
        playAudio("/home/nassim/NetBeansProjects/gameIhm/src/gameihm/sounds/animalName/"+currentLetter.toLowerCase()+"1Name.wav");
    }//GEN-LAST:event_animalNameLabelMouseClicked

    private void btnPrevLetterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevLetterMouseClicked
        // TODO add your handling code here:
        updateCurrentLetter(-1);
    }//GEN-LAST:event_btnPrevLetterMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        switchScreen(screenLearn);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        switchScreen(home);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void alphabetLetterBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alphabetLetterBMouseClicked
        // TODO add your handling code here:
        playAudio("/home/nassim/NetBeansProjects/gameIhm/src/gameihm/sounds/letters/Letter "+"B"+" - Phonics.wav");

    }//GEN-LAST:event_alphabetLetterBMouseClicked

    private void alphabetLetterCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alphabetLetterCMouseClicked
        playAudio("/home/nassim/NetBeansProjects/gameIhm/src/gameihm/sounds/letters/Letter "+"C"+" - Phonics.wav");

        // TODO add your handling code here:
    }//GEN-LAST:event_alphabetLetterCMouseClicked

    private void alphabetLetterDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alphabetLetterDMouseClicked
        playAudio("/home/nassim/NetBeansProjects/gameIhm/src/gameihm/sounds/letters/Letter "+"D"+" - Phonics.wav");

        // TODO add your handling code here:
    }//GEN-LAST:event_alphabetLetterDMouseClicked

    private void alphabetLetterEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alphabetLetterEMouseClicked
        // TODO add your handling code here:
        playAudio("/home/nassim/NetBeansProjects/gameIhm/src/gameihm/sounds/letters/Letter "+"E"+" - Phonics.wav");

    }//GEN-LAST:event_alphabetLetterEMouseClicked

    private void alphabetLetterFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alphabetLetterFMouseClicked
        // TODO add your handling code here:
        playAudio("/home/nassim/NetBeansProjects/gameIhm/src/gameihm/sounds/letters/Letter "+"F"+" - Phonics.wav");

    }//GEN-LAST:event_alphabetLetterFMouseClicked

    private void alphabetLetter6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alphabetLetter6MouseClicked
        // TODO add your handling code here:
        playAudio("/home/nassim/NetBeansProjects/gameIhm/src/gameihm/sounds/letters/Letter "+"G"+" - Phonics.wav");

    }//GEN-LAST:event_alphabetLetter6MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        game.pause();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        switchScreen(home);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        game.start();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void blackColorBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blackColorBtnMouseClicked
        // TODO add your handling code here:
        paint.setColor(new Color(5, 4, 0));
    }//GEN-LAST:event_blackColorBtnMouseClicked

    private void blueColorBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blueColorBtnMouseClicked
        // TODO add your handling code here:
        paint.setColor(new Color(22,110,252));
    }//GEN-LAST:event_blueColorBtnMouseClicked

    private void redColorBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redColorBtnMouseClicked
        // TODO add your handling code here:
        paint.setColor(new Color(252,22,60));
    }//GEN-LAST:event_redColorBtnMouseClicked

    private void yellowColorBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yellowColorBtnMouseClicked
        // TODO add your handling code here:
        paint.setColor(new Color(252,206,22));
    }//GEN-LAST:event_yellowColorBtnMouseClicked

    private void orangeColorBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orangeColorBtnMouseClicked
        // TODO add your handling code here:
        paint.setColor(new Color(252,110,22));
    }//GEN-LAST:event_orangeColorBtnMouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        paint.clear();
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        switchScreen(home);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void currentLetterToDrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentLetterToDrawMouseClicked
        // TODO add your handling code here:
        playAudio("/home/nassim/NetBeansProjects/gameIhm/src/gameihm/sounds/letters/Letter " + currentLetter + " - Phonics.wav");

    }//GEN-LAST:event_currentLetterToDrawMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        updateCurrentLetter(+1);
    }//GEN-LAST:event_jLabel5MouseClicked

    
    
    
    
    
    //methode to switch between screens
    private void switchScreen(JPanel panel) {
        screen.removeAll();
        screen.add(panel);
        screen.repaint();
        screen.revalidate();
    }
    
    // method to update the currentLetter
    private void updateCurrentLetter(int det) {
        /*        System.out.println((int)currentLetter.charAt(0));

        currentLetter = Character.toString((char)(65+(((int)currentLetter.charAt(0)+1)%91)%65));
        if((int)currentLetter.charAt(0) < 65)
            currentLetter = "Z"; */
        if(currentLetter == "Z" && det == 1)
            currentLetter = "A";
        else if (currentLetter == "A" && det == -1)
            currentLetter = "Z";
        else
            currentLetter = Character.toString((char)((int)currentLetter.charAt(0) + det));
        
        currentAnimal = (currentAnimal+det)%25;
        if(currentAnimal < 0)
            currentAnimal = 25;
        
        imgCurrentLetter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameihm/images/400/"+currentLetter+"1.png")));
        animalNameLabel.setText(animals[currentAnimal]);
        
        //updating letterToDraw
        currentLetterToDraw.setText(currentLetter + " " + currentLetter.toLowerCase());

    }
    
    private void playBackAudio(String path) {
        
        try {
            InputStream file = new FileInputStream(path);

            // create an audiostream from the inputstream
            backAudio = new AudioStream(file);

            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(backAudio);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void playAudio(String path) {
        
        try {
            InputStream file = new FileInputStream(path);

            // create an audiostream from the inputstream
            AudioStream audioStream = new AudioStream(file);

            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(audioStream);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alphabetLetter10;
    private javax.swing.JLabel alphabetLetter12;
    private javax.swing.JLabel alphabetLetter13;
    private javax.swing.JLabel alphabetLetter14;
    private javax.swing.JLabel alphabetLetter15;
    private javax.swing.JLabel alphabetLetter16;
    private javax.swing.JLabel alphabetLetter17;
    private javax.swing.JLabel alphabetLetter18;
    private javax.swing.JLabel alphabetLetter19;
    private javax.swing.JLabel alphabetLetter20;
    private javax.swing.JLabel alphabetLetter21;
    private javax.swing.JLabel alphabetLetter22;
    private javax.swing.JLabel alphabetLetter23;
    private javax.swing.JLabel alphabetLetter24;
    private javax.swing.JLabel alphabetLetter25;
    private javax.swing.JLabel alphabetLetter27;
    private javax.swing.JLabel alphabetLetter6;
    private javax.swing.JLabel alphabetLetter7;
    private javax.swing.JLabel alphabetLetter8;
    private javax.swing.JLabel alphabetLetter9;
    private javax.swing.JLabel alphabetLetterA;
    private javax.swing.JLabel alphabetLetterB;
    private javax.swing.JLabel alphabetLetterC;
    private javax.swing.JLabel alphabetLetterD;
    private javax.swing.JLabel alphabetLetterE;
    private javax.swing.JLabel alphabetLetterF;
    private javax.swing.JLabel animalNameLabel;
    private javax.swing.JLabel blackColorBtn;
    private javax.swing.JLabel blueColorBtn;
    private javax.swing.JLabel btn;
    private javax.swing.JLabel btn1;
    private javax.swing.JLabel btn3;
    private javax.swing.JLabel btnDraw;
    private javax.swing.JLabel btnLearn;
    private javax.swing.JLabel btnNextLetter;
    private javax.swing.JLabel btnPlay;
    private javax.swing.JLabel btnPrevLetter;
    private javax.swing.JLabel btnSingleLetterScreen;
    private javax.swing.JLabel currentLetterToDraw;
    private javax.swing.JLabel currentLetterToDraw2;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JPanel home;
    private javax.swing.JLabel imgCurrentLetter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel life;
    private javax.swing.JLabel orangeColorBtn;
    private javax.swing.JPanel paintArea;
    private javax.swing.JLabel redColorBtn;
    private javax.swing.JLabel score;
    private javax.swing.JLayeredPane screen;
    private javax.swing.JPanel screenDraw;
    private javax.swing.JPanel screenLearn;
    private javax.swing.JPanel screenLearnSingle;
    private javax.swing.JPanel screenPlay;
    private javax.swing.JLabel skyBackground;
    private javax.swing.JLabel skyBackground1;
    private javax.swing.JLabel target;
    private javax.swing.JLabel yellowColorBtn;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
